navbar:
  blog_title: "沧浪的博客"

index:
  banner_img: /img/bg.jpg
  slogan:
    text: "非淡泊无以明志，非宁静无以致远"

archive:
  banner_img: /img/bg.jpg

category:
  banner_img: /img/bg.jpg

tag:
  banner_img: /img/bg.jpg

page:
  banner_img: /img/bg.jpg

about:
  banner_img: /img/bg.jpg
  avatar: /img/avatar.jpg
  name: "沧浪"
  intro: "一名在读研究生，研究方向是图挖掘"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/canglang007", tip: "GitHub" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/WeChat.png" }
    - { class: "iconfont icon-qq-fill", qrcode: "/img/QQ.png" , tip: "QQ" }
    - { class: "iconfont icon-zhihu-fill", link: "https://www.zhihu.com/people/canglang007", tip: "知乎" }
    - { class: "iconfont icon-mail", link: "mailto:2097254505@qq.com", tip: "邮箱" }
